import Head from "next/head";
import Image from "next/image";
import { Caveat, Dosis } from "@next/font/google";

const dosis = Dosis({ subsets: ["latin"] });
const caveat = Caveat({ subsets: ["latin"]})

import bg from "../public/bg.jpeg";
import logo from "../public/avatar.jpg";

import Menu from '../components/Menu';
import About from '../components/About';

import { BsTwitter, BsLinkedin, BsGithub } from 'react-icons/bs';


export default function Home() {
  return (
    <>
      <Head>
        <title>RS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={dosis.style}>
        <Menu font={caveat.style} />
        <div
          className="relative z-0 bg-cover bg-center bg-no-repeat py-8"
          style={{ backgroundImage: `url(${bg.src})` }}
        >
          <div className="absolute inset-0 z-20 bg-gradient-to-r from-indigo-600 to-violet-500 bg-cover bg-center bg-no-repeat opacity-90"></div>

          <div className="mx-auto container relative z-30 pt-20 pb-12 sm:pt-56 sm:pb-48 lg:pt-64 lg:pb-48">
            <div className="flex flex-col items-center justify-center lg:flex-row">
              <Image
                src={logo}
                className="h-56 w-56 border-8 object-cover rounded-full z-10 shadow-2xl"
                alt="author"
              />
              <div className="w-1/2 pt-8 sm:pt-10 lg:pl-8 lg:pt-0">
                <h1 className="text-center font-header text-4xl text-white sm:text-left sm:text-5xl md:text-6xl">
                  Hello, I am Frontend Developer
                </h1>
                <div className="flex flex-col justify-center pt-3 sm:flex-row sm:pt-5 lg:justify-start">
                  <div className="flex items-center justify-center pl-0 sm:justify-start md:pl-1">
                    <p className="font-body text-lg uppercase text-white">
                      Let's connect
                    </p>
                    <div className="hidden sm:block">
                      <i className="bx bx-chevron-right text-3xl text-yellow"></i>
                    </div>
                  </div>
                  <div className="flex items-center justify-center pt-5 pl-2 sm:justify-start sm:pt-0">
                    <a href="/">
                      <BsLinkedin className="text-white text-2xl ml-4"/>
                    </a>
                    <a href="/">
                      <BsGithub className="text-white text-2xl ml-4"/>
                    </a>
                    <a href="/">
                      <BsTwitter className="text-white text-2xl ml-4"/>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <About />
      </main>
    </>
  );
}
